<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.d9AtUDr' shared service.

return $this->privates['.service_locator.d9AtUDr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'groupe' => ['privates', '.errored..service_locator.d9AtUDr.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator.d9AtUDr": it references class "App\\Entity\\Groupe" but no such service exists.'],
], [
    'groupe' => 'App\\Entity\\Groupe',
]);
