<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IgBh0pn' shared service.

return $this->privates['.service_locator.IgBh0pn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'etudiant' => ['privates', '.errored..service_locator.IgBh0pn.App\\Entity\\Etudiant', NULL, 'Cannot autowire service ".service_locator.IgBh0pn": it references class "App\\Entity\\Etudiant" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'etudiant' => 'App\\Entity\\Etudiant',
    'manager' => '?',
]);
