<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xxX8Fum' shared service.

return $this->privates['.service_locator.xxX8Fum'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'groupe' => ['privates', '.errored..service_locator.xxX8Fum.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator.xxX8Fum": it references class "App\\Entity\\Groupe" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'groupe' => 'App\\Entity\\Groupe',
    'manager' => '?',
]);
