<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jDiYOjU' shared service.

return $this->privates['.service_locator.jDiYOjU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'prof' => ['privates', '.errored..service_locator.jDiYOjU.App\\Entity\\Professeur', NULL, 'Cannot autowire service ".service_locator.jDiYOjU": it references class "App\\Entity\\Professeur" but no such service exists.'],
], [
    'prof' => 'App\\Entity\\Professeur',
]);
