<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FQnVRxn' shared service.

return $this->privates['.service_locator.FQnVRxn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\adminController::delete_etudiant' => ['privates', '.service_locator.ddtE.O9', 'get_ServiceLocator_DdtE_O9Service.php', true],
    'App\\Controller\\adminController::delete_groupe' => ['privates', '.service_locator.d9AtUDr', 'get_ServiceLocator_D9AtUDrService.php', true],
    'App\\Controller\\adminController::delete_tuteur' => ['privates', '.service_locator.jDiYOjU', 'get_ServiceLocator_JDiYOjUService.php', true],
    'App\\Controller\\adminController::edit_etudiant' => ['privates', '.service_locator.IgBh0pn', 'get_ServiceLocator_IgBh0pnService.php', true],
    'App\\Controller\\adminController::edit_groupe' => ['privates', '.service_locator.xxX8Fum', 'get_ServiceLocator_XxX8FumService.php', true],
    'App\\Controller\\adminController::edit_tuteur' => ['privates', '.service_locator.p_ki21R', 'get_ServiceLocator_PKi21RService.php', true],
    'App\\Controller\\reunionController::ajoutReunion' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\reunionController::reunion' => ['privates', '.service_locator.3iyKRwz', 'get_ServiceLocator_3iyKRwzService.php', true],
    'App\\Controller\\reunionController::show' => ['privates', '.service_locator.ltb0tYQ', 'get_ServiceLocator_Ltb0tYQService.php', true],
    'App\\Controller\\adminController:delete_etudiant' => ['privates', '.service_locator.ddtE.O9', 'get_ServiceLocator_DdtE_O9Service.php', true],
    'App\\Controller\\adminController:delete_groupe' => ['privates', '.service_locator.d9AtUDr', 'get_ServiceLocator_D9AtUDrService.php', true],
    'App\\Controller\\adminController:delete_tuteur' => ['privates', '.service_locator.jDiYOjU', 'get_ServiceLocator_JDiYOjUService.php', true],
    'App\\Controller\\adminController:edit_etudiant' => ['privates', '.service_locator.IgBh0pn', 'get_ServiceLocator_IgBh0pnService.php', true],
    'App\\Controller\\adminController:edit_groupe' => ['privates', '.service_locator.xxX8Fum', 'get_ServiceLocator_XxX8FumService.php', true],
    'App\\Controller\\adminController:edit_tuteur' => ['privates', '.service_locator.p_ki21R', 'get_ServiceLocator_PKi21RService.php', true],
    'App\\Controller\\reunionController:ajoutReunion' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\reunionController:reunion' => ['privates', '.service_locator.3iyKRwz', 'get_ServiceLocator_3iyKRwzService.php', true],
    'App\\Controller\\reunionController:show' => ['privates', '.service_locator.ltb0tYQ', 'get_ServiceLocator_Ltb0tYQService.php', true],
], [
    'App\\Controller\\adminController::delete_etudiant' => '?',
    'App\\Controller\\adminController::delete_groupe' => '?',
    'App\\Controller\\adminController::delete_tuteur' => '?',
    'App\\Controller\\adminController::edit_etudiant' => '?',
    'App\\Controller\\adminController::edit_groupe' => '?',
    'App\\Controller\\adminController::edit_tuteur' => '?',
    'App\\Controller\\reunionController::ajoutReunion' => '?',
    'App\\Controller\\reunionController::reunion' => '?',
    'App\\Controller\\reunionController::show' => '?',
    'App\\Controller\\adminController:delete_etudiant' => '?',
    'App\\Controller\\adminController:delete_groupe' => '?',
    'App\\Controller\\adminController:delete_tuteur' => '?',
    'App\\Controller\\adminController:edit_etudiant' => '?',
    'App\\Controller\\adminController:edit_groupe' => '?',
    'App\\Controller\\adminController:edit_tuteur' => '?',
    'App\\Controller\\reunionController:ajoutReunion' => '?',
    'App\\Controller\\reunionController:reunion' => '?',
    'App\\Controller\\reunionController:show' => '?',
]);
