<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.p_ki21R' shared service.

return $this->privates['.service_locator.p_ki21R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'professeur' => ['privates', '.errored..service_locator.p_ki21R.App\\Entity\\Professeur', NULL, 'Cannot autowire service ".service_locator.p_ki21R": it references class "App\\Entity\\Professeur" but no such service exists.'],
], [
    'manager' => '?',
    'professeur' => 'App\\Entity\\Professeur',
]);
