<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\adminController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\adminController.php';

$this->services['App\\Controller\\adminController'] = $instance = new \App\Controller\adminController(($this->privates['App\\Repository\\EtudiantRepository'] ?? $this->load('getEtudiantRepositoryService.php')), ($this->privates['App\\Repository\\ProfesseurRepository'] ?? $this->load('getProfesseurRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['App\\Repository\\GroupeRepository'] ?? $this->load('getGroupeRepositoryService.php')));

$instance->setContainer(($this->privates['.service_locator.CDOTD6.'] ?? $this->load('get_ServiceLocator_CDOTD6_Service.php'))->withContext('App\\Controller\\adminController', $this));

return $instance;
