<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUrJxnSi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUrJxnSi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUrJxnSi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUrJxnSi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUrJxnSi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UrJxnSi',
    'container.build_id' => 'b1f0379e',
    'container.build_time' => 1578353379,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUrJxnSi');
