<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMn1KA0r\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMn1KA0r/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMn1KA0r.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMn1KA0r\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMn1KA0r\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Mn1KA0r',
    'container.build_id' => '3be61c92',
    'container.build_time' => 1570738543,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMn1KA0r');
