<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUddRw5x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUddRw5x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUddRw5x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUddRw5x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUddRw5x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UddRw5x',
    'container.build_id' => '85a0b6ac',
    'container.build_time' => 1578907604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUddRw5x');
